baseurl: 

# Site settings
title: Kijkdoos
email: info@kijkdoos.tv
description: "Kijkdoos is een filmproductie & advertentiebedrijf gevestigd in Delft, maar werkt in vrijwel heel Nederland. Samen met u kunnen wij uw verhaal vertellen door middel van een visuele creatie."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Antoine Kooren
  pic: 1
  position: Founder/Filmer/Editor 
  social:
    - title: facebook
      url: https://www.facebook.com/antoine61
    - title: linkedin
      url: 	    

- name: Stijn Balk
  pic: 2
  position: Founder/Filmer/Editor
  social:
    - title: facebook
      url: https://www.facebook.com/stijn.balk
    - title: linkedin
      url: https://nl.linkedin.com/in/stijnbalk	  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: 


# Postal address (add as many lines as necessary)
address:
  - line: Spoorsingel 61
  - line: 2613 BA Delft

# Build settings
markdown: kramdown
permalink: pretty